version: '3.7'

services:
  ngauth:
    container_name: ngauth
    build:
      context: .
      args: 
        - "PAT=${PAT}"
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
    ports: 
      - "8082:80"
    networks:
      - local

networks:
  local:
    external: true