version: '3.7'

services:
  auth:
    image: registry.gitlab.com/notguiri/auth:#{IMG_TAG}#
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        max_attempts: 3
    environment:
      - ASPNETCORE_ENVIRONMENT=#{ASPNETCORE_ENVIRONMENT}#
      - GOOGLE_APPLICATION_CREDENTIALS=/data/service-account-file.json
    ports: 
      - "8082:80"
    networks:
      - backend
    volumes:
      - "#{LOCAL_AUTH_PATH}#:/data"

networks:
  backend:
    external: true